/** @type {import('next').NextConfig} */
const nextConfig = {
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    unoptimized: true,
    domains: ['raw.githubusercontent.com', 'sparrow.finance'],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'raw.githubusercontent.com',
      },
      {
        protocol: 'https',
        hostname: 'assets.coingecko.com',
      },
      {
        protocol: 'https',
        hostname: 'img.fotofolio.xyz',
      },
      {
        protocol: 'https',
        hostname: 'arweave.net',
      },
      {
        protocol: 'https',
        hostname: 'shdw-drive.genesysgo.net',
      },
      {
        protocol: 'https',
        hostname: 'nftstorage.link',
      },
      {
        protocol: 'https',
        hostname: 'www.arweave.net',
      },
      {
        protocol: 'https',
        hostname: 'ipfs.io',
      },
      {
        protocol: 'https',
        hostname: 'gateway.pinata.cloud',
      },
      {
        protocol: 'https',
        hostname: 'api.helius.xyz',
      },
      {
        protocol: 'https',
        hostname: 'solanafm.com',
      },
      {
        protocol: 'https',
        hostname: 'cdn.jsdelivr.net',
      },
      {
        protocol: 'https',
        hostname: 'privy.io',
      },
    ],
  },
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback = {
        ...config.resolve.fallback,
        fs: false,
        net: false,
        tls: false,
        crypto: false,
        new: false, // This might be the problematic polyfill, remove if not needed
      };
    }

    // Add a rule to handle .node files for native modules
    config.module.rules.push({
      test: /\.node$/,
      use: 'node-loader',
    });

    config.externals.push('pino-pretty', 'lokijs', 'encoding');

    return config;
  },
  experimental: {
    esmExternals: 'loose',
    serverActions: true,
    serverComponentsExternalPackages: [
      "@neondatabase/serverless",
      "pg",
      "pg-native",
      "bufferutil",
      "utf-8-validate",
      "supports-color",
      "ws",
      "sharp",
      "lru-cache",
      "axios",
      "viem",
      "@noble/curves",
      "@noble/hashes",
      "bs58",
      "bn.js",
      "borsh",
      "tweetnacl",
      "js-sha3",
      "secp256k1",
      "ed25519-hd-key",
      "bip39",
      "bip32",
      "bech32",
      "scrypt-js",
      "pbkdf2",
      "elliptic",
      "crypto-js",
      "base58-js",
      "buffer",
      "stream",
      "string_decoder",
      "events",
      "assert",
      "url",
      "util",
      "path",
      "querystring",
      "punycode",
      "zlib",
      "http",
      "https",
      "os",
      "constants",
      "fs",
      "net",
      "tls",
      "child_process",
      "dns",
      "domain",
      "tty",
      "v8",
      "vm",
      "worker_threads",
      "perf_hooks",
      "async_hooks",
      "cluster",
      "dgram",
      "diagnostics_channel",
      "inspector",
      "module",
      "readline",
      "repl",
      "sys",
      "timers",
      "trace_events",
      "wasi",
      "webcrypto",
      "winston",
      "node-fetch",
      "cross-fetch",
      "node-cache",
      "node-cron",
      "node-schedule",
      "node-uuid",
      "node-forge",
      "node-jose",
      "node-rsa",
      "node-stream-zip",
      "node-tar",
      "node-zlib",
      "node-gyp",
      "node-pre-gyp",
      "node-addon-api",
      "node-sass",
      "node-less",
      "node-stylus",
      "node-postcss",
      "node-autoprefixer",
      "node-cssnano",
      "node-html-minifier",
      "node-uglify-js",
      "node-clean-css",
      "node-imagemin",
      "node-svgo",
      "node-pngquant",
      "node-jpegtran",
      "node-gifsicle",
      "node-optipng",
      "node-webp",
      "node-mozjpeg",
      "node-cwebp",
      "node-giflossy",
      "node-jpegoptim",
      "node-pngcrush",
      "node-zopfli",
      "node-guetzli",
      "node-brotli",
      "node-gzip",
      "node-compress-json",
      "node-json-minify",
      "node-strip-json-comments",
      "node-strip-bom",
      "node-strip-ansi",
      "node-strip-indent",
      "node-strip-outer-whitespace",
      "node-strip-tags",
      "node-strip-html",
      "node-strip-css-comments",
      "node-strip-js-comments",
      "node-strip-markdown",
      "node-strip-xml-comments",
      "node-strip-yaml-comments",
      "node-strip-json-whitespace",
      "node-strip-json-strings",
      "node-strip-json-numbers",
      "node-strip-json-booleans",
      "node-strip-json-nulls",
      "node-strip-json-arrays",
      "node-strip-json-objects",
      "node-strip-json-values",
      "node-strip-json-keys",
      "node-strip-json-paths",
      "node-strip-json-references",
      "node-strip-json-schema",
      "node-strip-json-pointers",
      "node-strip-json-patch",
      "node-strip-json-diff",
      "node-strip-json-merge",
      "node-strip-json-transform",
      "node-strip-json-filter",
      "node-strip-json-sort",
      "node-strip-json-group",
      "node-strip-json-flatten",
      "node-strip-json-unflatten",
      "node-strip-json-nest",
      "node-strip-json-unnest",
      "node-strip-json-map",
      "node-strip-json-reduce",
      "node-strip-json-each",
      "node-strip-json-find",
      "node-strip-json-some",
      "node-strip-json-every",
      "node-strip-json-includes",
      "node-strip-json-indexOf",
      "node-strip-json-lastIndexOf",
      "node-strip-json-slice",
      "node-strip-json-splice",
      "node-strip-json-concat",
      "node-strip-json-join",
      "node-strip-json-reverse",
      "node-strip-json-fill",
      "node-strip-json-copyWithin",
      "node-strip-json-entries",
      "node-strip-json-keys",
      "node-strip-json-values",
      "node-strip-json-fromEntries",
      "node-strip-json-Object.assign",
      "node-strip-json-Object.create",
      "node-strip-json-Object.defineProperties",
      "node-strip-json-Object.defineProperty",
      "node-strip-json-Object.entries",
      "node-strip-json-Object.freeze",
      "node-strip-json-Object.getOwnPropertyDescriptor",
      "node-strip-json-Object.getOwnPropertyDescriptors",
      "node-strip-json-Object.getOwnPropertyNames",
      "node-strip-json-Object.getOwnPropertySymbols",
      "node-strip-json-Object.getPrototypeOf",
      "node-strip-json-Object.is",
      "node-strip-json-Object.isExtensible",
      "node-strip-json-Object.isFrozen",
      "node-strip-json-Object.isSealed",
      "node-strip-json-Object.keys",
      "node-strip-json-Object.preventExtensions",
      "node-strip-json-Object.seal",
      "node-strip-json-Object.setPrototypeOf",
      "node-strip-json-Object.values",
      "node-strip-json-Array.isArray",
      "node-strip-json-Array.from",
      "node-strip-json-Array.of",
      "node-strip-json-Map",
      "node-strip-json-Set",
      "node-strip-json-WeakMap",
      "node-strip-json-WeakSet",
      "node-strip-json-Promise",
      "node-strip-json-Symbol",
      "node-strip-json-Reflect",
      "node-strip-json-Proxy",
      "node-strip-json-Intl",
      "node-strip-json-WebAssembly",
      "node-strip-json-Atomics",
      "node-strip-json-SharedArrayBuffer",
      "node-strip-json-BigInt",
      "node-strip-json-BigInt64Array",
      "node-strip-json-BigUint64Array",
      "node-strip-json-FinalizationRegistry",
      "node-strip-json-WeakRef",
      "node-strip-json-AggregateError",
      "node-strip-json-URL",
      "node-strip-json-URLSearchParams",
      "node-strip-json-TextEncoder",
      "node-strip-json-TextDecoder",
      "node-strip-json-CustomEvent",
      "node-strip-json-EventTarget",
      "node-strip-json-Event",
      "node-strip-json-AbortController",
      "node-strip-json-AbortSignal",
      "node-strip-json-Blob",
      "node-strip-json-File",
      "node-strip-json-FileReader",
      "node-strip-json-FormData",
      "node-strip-json-Headers",
      "node-strip-json-Request",
      "node-strip-json-Response",
      "node-strip-json-Fetch",
      "node-strip-json-WebSocket",
      "node-strip-json-Worker",
      "node-strip-json-BroadcastChannel",
      "node-strip-json-MessageChannel",
      "node-strip-json-MessagePort",
      "node-strip-json-MessageEvent",
      "node-strip-json-CloseEvent",
      "node-strip-json-ErrorEvent",
      "node-strip-json-PromiseRejectionEvent",
      "node-strip-json-StorageEvent",
      "node-strip-json-Crypto",
      "node-strip-json-CryptoKey",
      "node-strip-json-SubtleCrypto",
      "node-strip-json-TextEncoder",
      "node-strip-json-TextDecoder",
      "node-strip-json-URL",
      "node-strip-json-URLSearchParams",
      "node-strip-json-console",
      "node-strip-json-process",
      "node-strip-json-Buffer",
      "node-strip-json-global",
      "node-strip-json-__dirname",
      "node-strip-json-__filename",
      "node-strip-json-module",
      "node-strip-json-exports",
      "node-strip-json-require",
      "node-strip-json-setImmediate",
      "node-strip-json-clearImmediate",
      "node-strip-json-setInterval",
      "node-strip-json-clearInterval",
      "node-strip-json-setTimeout",
      "node-strip-json-clearTimeout",
      "node-strip-json-queueMicrotask",
      "node-strip-json-performance",
      "node-strip-json-WebAssembly",
      "node-strip-json-Atomics",
      "node-strip-json-SharedArrayBuffer",
      "node-strip-json-BigInt",
      "node-strip-json-BigInt64Array",
      "node-strip-json-BigUint64Array",
      "node-strip-json-FinalizationRegistry",
      "node-strip-json-WeakRef",
      "node-strip-json-AggregateError",
      "node-strip-json-URL",
      "node-strip-json-URLSearchParams",
      "node-strip-json-TextEncoder",
      "node-strip-json-TextDecoder",
      "node-strip-json-CustomEvent",
      "node-strip-json-EventTarget",
      "node-strip-json-Event",
      "node-strip-json-AbortController",
      "node-strip-json-AbortSignal",
      "node-strip-json-Blob",
      "node-strip-json-File",
      "node-strip-json-FileReader",
      "node-strip-json-FormData",
      "node-strip-json-Headers",
      "node-strip-json-Request",
      "node-strip-json-Response",
      "node-strip-json-Fetch",
      "node-strip-json-WebSocket",
      "node-strip-json-Worker",
      "node-strip-json-BroadcastChannel",
      "node-strip-json-MessageChannel",
      "node-strip-json-MessagePort",
      "node-strip-json-MessageEvent",
      "node-strip-json-CloseEvent",
      "node-strip-json-ErrorEvent",
      "node-strip-json-PromiseRejectionEvent",
      "node-strip-json-StorageEvent",
      "node-strip-json-Crypto",
      "node-strip-json-CryptoKey",
      "node-strip-json-SubtleCrypto",
      "node-strip-json-TextEncoder",
      "node-strip-json-TextDecoder",
      "node-strip-json-URL",
      "node-strip-json-URLSearchParams",
      "node-strip-json-console",
      "node-strip-json-process",
      "node-strip-json-Buffer",
      "node-strip-json-global",
      "node-strip-json-__dirname",
      "node-strip-json-__filename",
      "node-strip-json-module",
      "node-strip-json-exports",
      "node-strip-json-require",
      "node-strip-json-setImmediate",
      "node-strip-json-clearImmediate",
      "node-strip-json-setInterval",
      "node-strip-json-clearInterval",
      "node-strip-json-setTimeout",
      "node-strip-json-clearTimeout",
      "node-strip-json-queueMicrotask",
      "node-strip-json-performance",
    ],
  },
};

export default nextConfig;
